# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-05 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='students',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(upload_to='courses/%Y/%m', verbose_name='头像'),
        ),
    ]
